"""生成演示用合成数据（**不是真实评级数据**）。

用法
----
.. code-block:: bash

    python scripts/make_sample_data.py

输出
----
* ``data/sample/ratings_sample.csv`` —— 事件式主权评级记录
* ``data/sample/macro_sample.csv``   —— 与之对齐的宏观面板

设计原则
--------
1. **完全确定性**：固定随机种子，同一版本代码生成的数据逐字节一致，可复现。
2. **不是真实数据**：所有输出均带 ``provenance = synthetic_demo_only`` 标记列；
   国家代码与名称仅用于演示，评分数值与任何机构的真实评级无关。
3. **结构真实**：数据刻意模拟真实数据的若干「麻烦之处」，用于测试清洗流程——
   评级行动是事件式的（只在变化时记录）、三家机构存在系统性差异、
   展望含信用观察状态、部分评级带未邀约修饰符、宏观指标存在结构性缺失。
4. **有统计信号**：宏观指标围绕评级水平生成，使演示流水线能够跑出非平凡的
   回归系数与预测能力（否则演示会退化为纯噪声）。
"""

from __future__ import annotations

import sys
from pathlib import Path

import numpy as np
import pandas as pd

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from src.config import get_path  # noqa: E402
from src.features.rating_scale import score_to_grade  # noqa: E402

SEED = 20240625
YEARS = list(range(2000, 2024))
PROVENANCE = "synthetic_demo_only"
NOTE = (
    "SYNTHETIC DEMO DATA — generated by scripts/make_sample_data.py. "
    "NOT real sovereign ratings. Do not use for empirical conclusions."
)

# (ISO3, 名称, 演示用基准信用质量)
COUNTRIES: list[tuple[str, str, int]] = [
    ("USA", "United States", 21),
    ("DEU", "Germany", 21),
    ("JPN", "Japan", 18),
    ("GBR", "United Kingdom", 20),
    ("FRA", "France", 19),
    ("ITA", "Italy", 14),
    ("ESP", "Spain", 16),
    ("KOR", "Korea, Rep.", 16),
    ("CHN", "China", 15),
    ("BRA", "Brazil", 10),
    ("MEX", "Mexico", 12),
    ("TUR", "Turkiye", 8),
    ("ZAF", "South Africa", 10),
    ("IDN", "Indonesia", 12),
    ("IND", "India", 12),
    ("ARG", "Argentina", 4),
    ("RUS", "Russian Federation", 9),
    ("NGA", "Nigeria", 7),
]

# 机构差异：(持续性偏置, 每年发生评级行动的概率)
AGENCIES: dict[str, tuple[float, float]] = {
    "S&P": (0.25, 0.45),
    "Moody's": (-0.20, 0.36),
    "Fitch": (-0.05, 0.30),
}

# 危机年份对特定国家的额外冲击（演示「评级在经济危机中集中下调」）
CRISIS_SHOCKS: dict[str, dict[int, float]] = {
    "ITA": {2011: -1.6, 2012: -1.2},
    "ESP": {2011: -1.4, 2012: -1.0},
    "ARG": {2001: -6.0, 2002: -2.5, 2014: -1.5, 2018: -2.0, 2019: -1.5, 2020: -1.8},
    "TUR": {2016: -1.6, 2018: -1.8, 2020: -1.2},
    "RUS": {2014: -2.0, 2015: -1.5, 2022: -2.5},
    "BRA": {2015: -1.8, 2016: -1.4},
    "ZAF": {2020: -1.6},
    "NGA": {2016: -1.4, 2020: -1.6},
    "IDN": {2013: -1.2},
    "MEX": {2020: -1.0},
}


def _ar1(rng: np.random.Generator, n: int, rho: float, sigma: float) -> np.ndarray:
    """生成平稳 AR(1) 过程。"""
    series = np.zeros(n)
    for i in range(1, n):
        series[i] = rho * series[i - 1] + rng.normal(0.0, sigma)
    return series


def build_rating_paths() -> tuple[dict[str, np.ndarray], pd.DataFrame]:
    """生成每个国家与机构的评级路径，并展开为事件式评级记录。"""
    rng = np.random.default_rng(SEED)
    n_years = len(YEARS)

    common = _ar1(rng, n_years, rho=0.78, sigma=0.55)
    common -= common.mean()

    country_paths: dict[str, np.ndarray] = {}
    records: list[dict[str, object]] = []

    for iso3, name, base in COUNTRIES:
        idio = _ar1(rng, n_years, rho=0.82, sigma=0.55)
        crisis = np.array([CRISIS_SHOCKS.get(iso3, {}).get(year, 0.0) for year in YEARS])
        # 危机冲击具有持续性：评级下调后通常需要多年才能修复
        crisis_persist = np.zeros(n_years)
        for i in range(1, n_years):
            crisis_persist[i] = 0.45 * crisis_persist[i - 1] + crisis[i]
        latent = base + 0.55 * common + idio + crisis + crisis_persist
        country_paths[iso3] = np.clip(np.rint(latent), 1, 21).astype(int)

        for agency, (bias, action_prob) in AGENCIES.items():
            agency_idio = _ar1(rng, n_years, rho=0.75, sigma=0.42)
            agency_latent = latent + bias + agency_idio
            published: int | None = None
            for index, year in enumerate(YEARS):
                candidate = int(np.clip(np.rint(agency_latent[index]), 1, 21))
                first_year = index == 0
                if not first_year and candidate == published:
                    continue
                if not first_year and rng.random() > action_prob:
                    continue
                published = candidate
                gap = agency_latent[index] - candidate
                outlook = "Stable"
                if gap > 0.65:
                    outlook = "Positive"
                elif gap < -0.65:
                    outlook = "Negative"
                if outlook in {"Positive", "Negative"} and rng.random() < 0.07:
                    outlook = f"Watch-{outlook}"
                if outlook == "Stable" and rng.random() < 0.05:
                    outlook = "Developing"

                month = int(rng.integers(1, 13))
                day = int(rng.integers(1, 28))
                records.append(
                    {
                        "country_iso3": iso3,
                        "country_name": name,
                        "year": year,
                        "agency": agency,
                        "rating": score_to_grade(candidate, agency),
                        "outlook": outlook,
                        "action": "assign",
                        "action_date": f"{year}-{month:02d}-{day:02d}",
                        "rating_score": candidate,
                        "provenance": PROVENANCE,
                        "data_note": NOTE,
                    }
                )

    ratings = pd.DataFrame.from_records(records)
    # 让 action 列反映真实的迁移方向
    ratings = ratings.sort_values(["country_iso3", "agency", "year"]).reset_index(drop=True)
    previous = ratings.groupby(["country_iso3", "agency"])["rating_score"].shift(1)
    ratings["action"] = np.where(
        previous.isna(),
        "assign",
        np.where(ratings["rating_score"] > previous, "upgrade", "downgrade"),
    )
    return country_paths, ratings


def inject_dirty_values(ratings: pd.DataFrame, rng: np.random.Generator) -> pd.DataFrame:
    """注入真实数据中常见的「脏值」，用于演示清洗逻辑。"""
    frame = ratings.copy()

    # 1) 未邀约评级后缀 "u"（S&P / Fitch 常见）
    mask = (frame["agency"].isin(["S&P", "Fitch"])) & (np.arange(len(frame)) % 17 == 0)
    frame.loc[mask, "rating"] = frame.loc[mask, "rating"] + "u"

    # 2) 信用观察记号的不同写法
    mask = (
        (frame["agency"] == "Fitch")
        & (frame["outlook"] == "Negative")
        & (np.arange(len(frame)) % 11 == 0)
    )
    frame.loc[mask, "outlook"] = "CW-Negative"
    mask = (
        (frame["agency"] == "Moody's")
        & (frame["outlook"] == "Positive")
        & (np.arange(len(frame)) % 13 == 0)
    )
    frame.loc[mask, "outlook"] = "Positive Watch"

    # 3) 展望缺失 / 写为 n/a
    mask = np.arange(len(frame)) % 29 == 0
    frame.loc[mask, "outlook"] = None
    mask = np.arange(len(frame)) % 37 == 5
    frame.loc[mask, "outlook"] = "n/a"

    # 4) action_date 缺失（部分历史数据没有精确日期）
    mask = np.arange(len(frame)) % 41 == 3
    frame.loc[mask, "action_date"] = None

    return frame.sample(frac=1.0, random_state=int(rng.integers(0, 2**31 - 1))).reset_index(
        drop=True
    )


def build_macro_panel(
    country_paths: dict[str, np.ndarray], rng: np.random.Generator
) -> pd.DataFrame:
    """围绕评级水平生成与之相关的宏观面板。"""
    records: list[dict[str, object]] = []
    for iso3, name, _base in COUNTRIES:
        path = country_paths[iso3].astype(float)
        fx_level = float(np.exp(rng.normal(1.5, 1.8)))
        for index, year in enumerate(YEARS):
            score = float(path[index])
            deviation = score - 10.0

            gdp_growth = 1.1 + 0.34 * deviation + rng.normal(0, 1.6)
            inflation = max(-3.0, 7.8 - 0.48 * deviation + rng.normal(0, 2.4))
            gov_debt_gdp = float(np.clip(112 - 4.2 * deviation + rng.normal(0, 8), 5, 260))
            external_debt_gni = float(np.clip(92 - 3.6 * deviation + rng.normal(0, 10), 3, 220))
            reserves_months = float(np.clip(4.2 + 0.34 * deviation + rng.normal(0, 1.2), 0.1, 30))
            current_account = float(np.clip(0.42 * deviation + rng.normal(0, 2.5), -20, 25))
            exports_gdp = float(np.clip(30 + 1.6 * deviation + rng.normal(0, 6), 5, 200))
            gdp_per_capita = float(np.exp(8.2 + 0.16 * deviation + rng.normal(0, 0.15)))
            depreciation = float(np.clip(2.0 - 0.30 * deviation + rng.normal(0, 6), -15, 60))
            fx_level = max(fx_level * (1.0 + depreciation / 100.0), 1e-4)
            real_rate = float(np.clip(1.5 - 0.25 * deviation + rng.normal(0, 3), -10, 40))
            spread = float(np.clip(np.exp(5.4 - 0.30 * deviation + rng.normal(0, 0.35)), 8, 3000))

            record: dict[str, object] = {
                "country_iso3": iso3,
                "country_name": name,
                "year": year,
                "gdp_growth": gdp_growth,
                "inflation": inflation,
                "gov_debt_gdp": gov_debt_gdp,
                "external_debt_gni": external_debt_gni,
                "reserves_months_imports": reserves_months,
                "current_account_gdp": current_account,
                "exports_gdp": exports_gdp,
                "gdp_per_capita": gdp_per_capita,
                "fx_official_rate": fx_level,
                "real_interest_rate": real_rate,
                "spread_bps": spread,
                "provenance": PROVENANCE,
                "data_note": NOTE,
            }
            for indicator, centre in (
                ("voice_accountability", 0.0),
                ("political_stability", -0.2),
                ("government_effectiveness", 0.2),
                ("regulatory_quality", 0.15),
                ("rule_of_law", 0.1),
                ("control_corruption", 0.05),
            ):
                record[indicator] = float(
                    np.clip(centre + 0.11 * deviation + rng.normal(0, 0.30), -2.5, 2.5)
                )
            records.append(record)

    macro = pd.DataFrame.from_records(records)

    # 结构性缺失：WGI 早期年份覆盖不全，少数宏观指标偶有间断
    missing_rng = np.random.default_rng(SEED + 1)
    early = macro["year"] <= 2001
    for column in (
        "voice_accountability",
        "political_stability",
        "government_effectiveness",
        "regulatory_quality",
        "rule_of_law",
        "control_corruption",
    ):
        drop_mask = early & (missing_rng.random(len(macro)) < 0.35)
        macro.loc[drop_mask, column] = np.nan

    for column in ("inflation", "gov_debt_gdp", "reserves_months_imports", "exports_gdp"):
        drop_mask = missing_rng.random(len(macro)) < 0.035
        macro.loc[drop_mask, column] = np.nan

    return macro.sort_values(["country_iso3", "year"]).reset_index(drop=True)


def main() -> int:
    """生成并写出两份示例数据。"""
    sample_dir = get_path("sample")
    sample_dir.mkdir(parents=True, exist_ok=True)
    rng = np.random.default_rng(SEED)

    country_paths, ratings = build_rating_paths()
    ratings = inject_dirty_values(ratings, rng)
    macro = build_macro_panel(country_paths, rng)

    ratings_path = sample_dir / "ratings_sample.csv"
    macro_path = sample_dir / "macro_sample.csv"
    ratings.to_csv(ratings_path, index=False, encoding="utf-8-sig")
    macro.to_csv(macro_path, index=False, encoding="utf-8-sig")

    print(f"[ok] 写出 {ratings_path}  ({len(ratings)} 行 × {ratings.shape[1]} 列)")
    print(f"[ok] 写出 {macro_path}  ({len(macro)} 行 × {macro.shape[1]} 列)")
    print(
        "[warn] 以上均为**合成演示数据**（provenance="
        f"{PROVENANCE}），不是真实主权评级，禁止用于实证结论。"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
